# -*- coding: utf-8 -*-
"""Catálogo BVL: ticker -> sector.
Base: listado oficial BVL 14/09/2026. Sectores de "Diversas" reclasificados
con GICS (grid.xlsx). "Bancos y Financieras" renombrado a "Financieras".
"""

BVL_SECTORS = {
    'AENZAC1': 'Industriales',
    'AGMR': 'Mineras',
    'AIBC1': 'Industriales',
    'AIHC1': 'Industriales',
    'AIPC1': 'Inmobiliario',
    'ALFINAC1': 'Financieras',
    'ALFINBC1': 'Financieras',
    'ALICORC1': 'Industriales',
    'ALICORI1': 'Industriales',
    'ANDAHUC1': 'Agrario',
    'ANDEXAC1': 'Mineras',
    'ANDEXBC1': 'Mineras',
    'ASJUANC1': 'Agrario',
    'ASSAINC1': 'Diversas',
    'ATACOAC1': 'Mineras',
    'ATACOBC1': 'Mineras',
    'AUGUSC1': 'Seguros',
    'AUNA': 'Salud',
    'AUNIONC1': 'Agrario',
    'AUSTRAC1': 'Industriales',
    'AVLASGC1': 'Seguros',
    'AZZAROC1': 'Diversas',
    'BACKUAC1': 'Industriales',
    'BACKUAC2': 'Industriales',
    'BACKUBC1': 'Industriales',
    'BACKUBC2': 'Industriales',
    'BACKUSI1': 'Industriales',
    'BACKUSI2': 'Industriales',
    'BAMC1': 'Materiales',
    'BANCOMC1': 'Financieras',
    'BANFALC1': 'Financieras',
    'BAP': 'Financieras',
    'BBVAC1': 'Financieras',
    'BCIPEC1': 'Financieras',
    'BIFC1': 'Financieras',
    'BOCPEC1': 'Financieras',
    'BPICHC1': 'Financieras',
    'BPICHPC1': 'Financieras',
    'BRIPLEC1': 'Financieras',
    'BROCALC1': 'Mineras',
    'BROCALI1': 'Mineras',
    'BUENAVC1': 'Mineras',
    'BUENAVI1': 'Mineras',
    'BVLC1': 'Diversas',
    'BVN': 'Holdings / ADR',
    'CARDIFC1': 'Seguros',
    'CARTAVC1': 'Agrario',
    'CASAGRC1': 'Agrario',
    'CASTROC1': 'Mineras',
    'CASTROI1': 'Mineras',
    'CAVALIC1': 'Financieras',
    'CAYALTC1': 'Agrario',
    'CDPR': 'Mineras',
    'CESCEPC1': 'Seguros',
    'CHIQUIC1': 'Agrario',
    'CHUBSGC1': 'Seguros',
    'CHUCARC1': 'Agrario',
    'CITIBKC1': 'Financieras',
    'CMAQPC1': 'Financieras',
    'COCESUC1': 'Industriales',
    'COCESUI1': 'Fondos de Inversión',
    'COFIDCC1': 'Financieras',
    'COLCAC1': 'Diversas',
    'COMPARC1': 'Financieras',
    'CONCESI1': 'Fondos de Inversión',
    'COPENC1': 'Diversas',
    'CORAREC1': 'Industriales',
    'CORAREI1': 'Industriales',
    'CPAC': 'Holdings / ADR',
    'CPACASC1': 'Industriales',
    'CPACASI1': 'Industriales',
    'CRANDEC1': 'Financieras',
    'CRECAPC1': 'Financieras',
    'CRECERC1': 'Seguros',
    'CREDITC1': 'Financieras',
    'CRETEXC1': 'Industriales',
    'CRETEXI1': 'Industriales',
    'CUMBRAC1': 'Industriales',
    'CVERDEC1': 'Mineras',
    'DESXXIC1': 'Diversas',
    'DUNENC1': 'Diversas',
    'ECU': 'Mineras',
    'EDUNASC1': 'Servicios Públicos',
    'EFECTIC1': 'Financieras',
    'EGEPIBC1': 'Servicios Públicos',
    'EGESUBC1': 'Servicios Públicos',
    'ELCOMEI1': 'Industriales',
    'ELECPBC1': 'Servicios Públicos',
    'ELESUDC1': 'Servicios Públicos',
    'ENGIEC1': 'Servicios Públicos',
    'ENPACIC1': 'Servicios Públicos',
    'ENPACII1': 'Fondos de Inversión',
    'EPUNOBC1': 'Servicios Públicos',
    'ESUREBC1': 'Servicios Públicos',
    'ETERNII1': 'Industriales',
    'ETNAI1': 'Industriales',
    'EXALMC1': 'Industriales',
    'EXPERTC1': 'Diversas',
    'FANUPEC1': 'Agrario',
    'FCONFIC1': 'Financieras',
    'FCREDIC1': 'Financieras',
    'FERREYC1': 'Industriales',
    'FIBCCAP': 'FIBRA / Inmobiliario',
    'FIBPRIME': 'FIBRA / Inmobiliario',
    'FILAMEI1': 'Fondos de Inversión',
    'FINTFCC1': 'Financieras',
    'FOSPACC1': 'Mineras',
    'FOSSALC1': 'Materiales',
    'FOSSALI1': 'Fondos de Inversión',
    'FPROEMC1': 'Financieras',
    'FPROEMP1': 'Financieras',
    'FUTURAC1': 'Diversas',
    'FUTURAI1': 'Fondos de Inversión',
    'GANSALC1': 'Agrario',
    'GBVLAC1': 'Financieras',
    'GBVLBC1': 'Financieras',
    'GLORIAI1': 'Industriales',
    'GNBC1': 'Financieras',
    'GNBC2': 'Financieras',
    'GRHOLDC1': 'Inmobiliario',
    'HABITAC1': 'AFP',
    'HERMESC1': 'Industriales',
    'HIDRA2C1': 'Servicios Públicos',
    'HIDROSI1': 'Industriales',
    'ICBCC1': 'Financieras',
    'IEQSAI1': 'Industriales',
    'IFS': 'Holdings / ADR',
    'IIDEC1': 'Diversas',
    'IIDEI1': 'Fondos de Inversión',
    'INCRAIC1': 'Diversas',
    'INDECOI1': 'Industriales',
    'INFIXPC1': 'Financieras',
    'INRETC1': 'Holdings / ADR',
    'INSURC1': 'Seguros',
    'INTEGRC1': 'AFP',
    'INTERBC1': 'Financieras',
    'INTPEBC1': 'Servicios Públicos',
    'INTPECC1': 'Servicios Públicos',
    'INTSEGC1': 'Seguros',
    'INVCENC1': 'Inmobiliario',
    'INVCO2C1': 'Diversas',
    'INVCORI1': 'Fondos de Inversión',
    'INVERPC1': 'Diversas',
    'INVERTC1': 'Diversas',
    'INVFALC1': 'Financieras',
    'IPCHAC1': 'Industriales',
    'IPCHBC1': 'Industriales',
    'ISICC1': 'Inmobiliario',
    'JPMORGC1': 'Diversas',
    'LAIVEBC1': 'Industriales',
    'LAREDOC1': 'Agrario',
    'LIBSEGC1': 'Seguros',
    'LUISAI1': 'Mineras',
    'LUSURC1': 'Servicios Públicos',
    'MAPFSGC1': 'Seguros',
    'MIBANC1': 'Financieras',
    'MICHEI1': 'Industriales',
    'MINCORC1': 'Mineras',
    'MINCORI1': 'Mineras',
    'MINSURI1': 'Mineras',
    'MIRL': 'Mineras',
    'MITSUFC1': 'Financieras',
    'MOROCOC1': 'Mineras',
    'MOROCOI1': 'Mineras',
    'NACSEGC1': 'Seguros',
    'NEXAPEC1': 'Mineras',
    'NEXAPEI1': 'Mineras',
    'NUAM': 'Holdings / ADR',
    'ORYGENC1': 'Servicios Públicos',
    'PACIFIC1': 'Seguros',
    'PALOALC1': 'Diversas',
    'PARAMOC1': 'Agrario',
    'PERENAC1': 'Servicios Públicos',
    'PERENBC1': 'Servicios Públicos',
    'PETROBC1': 'Industriales',
    'PHTBC1': 'Inmobiliario',
    'PIURAC1': 'Industriales',
    'PIURAI1': 'Industriales',
    'PLUZENC1': 'Servicios Públicos',
    'PML': 'Mineras',
    'PODERC1': 'Mineras',
    'POMALCC1': 'Agrario',
    'PORTAC1': 'Inmobiliario',
    'POSITIC1': 'Seguros',
    'POSITVC1': 'Seguros',
    'PPX': 'Mineras',
    'PRIMAC1': 'AFP',
    'PROFUTC1': 'AFP',
    'PROTECC1': 'Seguros',
    'PUCALAC1': 'Agrario',
    'PVTBC1': 'Diversas',
    'QAPAQC1': 'Financieras',
    'QUALSGC1': 'Seguros',
    'QUIMPAC1': 'Industriales',
    'QUIMPAI1': 'Industriales',
    'RBCAC1': 'Diversas',
    'RBCBC1': 'Financieras',
    'RECORDI1': 'Industriales',
    'REG': 'Mineras',
    'RIMSEGC1': 'Seguros',
    'RIO': 'Mineras',
    'RVIA5BC1': 'Industriales',
    'SAGAC1': 'Consumo Discrecional',
    'SANC1': 'Financieras',
    'SANFINC1': 'Financieras',
    'SANGABC1': 'Servicios Públicos',
    'SANTCOC1': 'Financieras',
    'SCCO': 'Mineras',
    'SCOTIAC1': 'Financieras',
    'SEALDC1': 'Servicios Públicos',
    'SEDAPBC1': 'Servicios Públicos',
    'SHOUGEC1': 'Servicios Públicos',
    'SHPC1': 'Mineras',
    'SIDERC1': 'Industriales',
    'SNCRISC1': 'Industriales',
    'SNJACIC1': 'Agrario',
    'SNJUANC1': 'Industriales',
    'SNJUANI1': 'Industriales',
    'SOLUCIC1': 'Diversas',
    'SPCCPI1': 'Mineras',
    'SPCCPI2': 'Mineras',
    'STG': 'Holdings / ADR',
    'TEF': 'Holdings / ADR',
    'TELCAAC1': 'Servicios Públicos',
    'TELCABC1': 'Servicios Públicos',
    'TOTALSC1': 'Financieras',
    'TRADIC1': 'Diversas',
    'TUMANC1': 'Agrario',
    'UNACEMC1': 'Materiales',
    'UNITEXC1': 'Industriales',
    'UNITEXI1': 'Industriales',
    'VIVSEGC1': 'Seguros',
    'VOLCAAC1': 'Mineras',
    'VOLCABC1': 'Mineras',
}

BVL_TICKERS = sorted(BVL_SECTORS.keys())
