# -*- coding: utf-8 -*-
"""Catálogo BVL: ticker -> sector y ticker -> nombre.
Incluye acciones peruanas (listado oficial) + valores extranjeros
(acciones y ETFs internacionales listados en la BVL).
"""

BVL_SECTORS = {
    'AAL': 'Consumo discrecional',
    'AAPL': 'Tecnología',
    'AAPU': 'ETF internacional',
    'ABNB': 'Consumo discrecional',
    'ABT': 'Salud',
    'ABX': 'Materiales',
    'ACNUS': 'Tecnología',
    'ACWDUS': 'ETF internacional',
    'ACWI': 'ETF internacional',
    'ACWX': 'ETF internacional',
    'ADBE': 'Tecnología',
    'ADI': 'Tecnología',
    'AEM': 'Otros (internacional)',
    'AENZAC1': 'Industriales',
    'AGG': 'ETF internacional',
    'AGGG': 'ETF internacional',
    'AGGU': 'ETF internacional',
    'AGIXUS': 'ETF internacional',
    'AGMR': 'Mineras',
    'AGUASAUS': 'Otros (internacional)',
    'AIBC1': 'Industriales',
    'AIHC1': 'Industriales',
    'AIPC1': 'Inmobiliario',
    'AIQ': 'ETF internacional',
    'ALFINAC1': 'Financieras',
    'ALFINBC1': 'Financieras',
    'ALICORC1': 'Industriales',
    'ALICORI1': 'Industriales',
    'AMAT': 'Tecnología',
    'AMD': 'Tecnología',
    'AMUU': 'ETF internacional',
    'AMZN': 'Consumo discrecional',
    'AMZU': 'ETF internacional',
    'ANDAHUC1': 'Agrario',
    'ANDEXAC1': 'Mineras',
    'ANDEXBC1': 'Mineras',
    'ANDINBUS': 'Otros (internacional)',
    'ANETUS': 'Tecnología',
    'APOUS': 'Financiero',
    'APP': 'Tecnología',
    'ARGT': 'ETF internacional',
    'ARKF': 'ETF internacional',
    'ARKG': 'ETF internacional',
    'ARKK': 'ETF internacional',
    'ARKQ': 'ETF internacional',
    'ARKW': 'ETF internacional',
    'ARKX': 'ETF internacional',
    'ASJUANC1': 'Agrario',
    'ASML': 'Tecnología',
    'ASSAINC1': 'Diversas',
    'ATACOAC1': 'Mineras',
    'ATACOBC1': 'Mineras',
    'AUGUSC1': 'Seguros',
    'AUNA': 'Salud',
    'AUNIONC1': 'Agrario',
    'AUSTRAC1': 'Industriales',
    'AVGO': 'Tecnología',
    'AVL': 'ETF internacional',
    'AVLASGC1': 'Seguros',
    'AXP': 'Financiero',
    'AZZAROC1': 'Diversas',
    'BA': 'Industrial',
    'BABAUS': 'Consumo discrecional',
    'BAC': 'Financiero',
    'BACKUAC1': 'Industriales',
    'BACKUAC2': 'Industriales',
    'BACKUBC1': 'Industriales',
    'BACKUBC2': 'Industriales',
    'BACKUSI1': 'Industriales',
    'BACKUSI2': 'Industriales',
    'BAI': 'ETF internacional',
    'BAMC1': 'Materiales',
    'BANCOMC1': 'Financieras',
    'BANFALC1': 'Financieras',
    'BAP': 'Financieras',
    'BBVA': 'Otros (internacional)',
    'BBVAC1': 'Financieras',
    'BCIPEC1': 'Financieras',
    'BCIUS': 'Otros (internacional)',
    'BIDU': 'Otros (internacional)',
    'BIFC1': 'Financieras',
    'BITO': 'ETF internacional',
    'BITU': 'ETF internacional',
    'BITX': 'ETF internacional',
    'BKLN': 'ETF internacional',
    'BKNG': 'Consumo discrecional',
    'BLK': 'Financiero',
    'BLTN': 'ETF internacional',
    'BMY': 'Salud',
    'BNDW': 'ETF internacional',
    'BOCPEC1': 'Financieras',
    'BOGOTAUS': 'Otros (internacional)',
    'BOIL': 'ETF internacional',
    'BOTZ': 'ETF internacional',
    'BPICHC1': 'Financieras',
    'BPICHPC1': 'Financieras',
    'BRIPLEC1': 'Financieras',
    'BRK/B': 'Otros (internacional)',
    'BROCALC1': 'Mineras',
    'BROCALI1': 'Mineras',
    'BRZU': 'ETF internacional',
    'BS0A': 'ETF internacional',
    'BS28': 'ETF internacional',
    'BS29': 'ETF internacional',
    'BS30': 'ETF internacional',
    'BS8A': 'ETF internacional',
    'BS9A': 'ETF internacional',
    'BSANTAUS': 'Otros (internacional)',
    'BTCCU': 'ETF internacional',
    'BTCO': 'ETF internacional',
    'BUENAVC1': 'Mineras',
    'BUENAVI1': 'Mineras',
    'BUG': 'ETF internacional',
    'BVLC1': 'Diversas',
    'BVN': 'Holdings / ADR',
    'C': 'Financiero',
    'CAPUS': 'Otros (internacional)',
    'CARDIFC1': 'Seguros',
    'CARTAVC1': 'Agrario',
    'CASAGRC1': 'Agrario',
    'CASTROC1': 'Mineras',
    'CASTROI1': 'Mineras',
    'CAT': 'Industrial',
    'CAVALIC1': 'Financieras',
    'CAYALTC1': 'Agrario',
    'CBU0': 'ETF internacional',
    'CBU7': 'ETF internacional',
    'CCL': 'Otros (internacional)',
    'CCOUS': 'Otros (internacional)',
    'CCUUS': 'Otros (internacional)',
    'CDPR': 'Mineras',
    'CELSIAUS': 'Otros (internacional)',
    'CEMARGUS': 'Otros (internacional)',
    'CEMB': 'ETF internacional',
    'CENCOSUS': 'Otros (internacional)',
    'CENMALUS': 'Otros (internacional)',
    'CESCEPC1': 'Seguros',
    'CHILEUS': 'Otros (internacional)',
    'CHIQUIC1': 'Agrario',
    'CHUBSGC1': 'Seguros',
    'CHUCARC1': 'Agrario',
    'CIBESTUS': 'Otros (internacional)',
    'CIBR': 'ETF internacional',
    'CIBR1US': 'ETF internacional',
    'CIND': 'ETF internacional',
    'CITIBKC1': 'Financieras',
    'CJPU': 'ETF internacional',
    'CMAQPC1': 'Financieras',
    'CMG': 'Consumo discrecional',
    'CMPCUS': 'Otros (internacional)',
    'CNDX': 'ETF internacional',
    'COCESUC1': 'Industriales',
    'COCESUI1': 'Fondos de Inversión',
    'COFIDCC1': 'Financieras',
    'COIN': 'Financiero',
    'COLBUNUS': 'Otros (internacional)',
    'COLCAC1': 'Diversas',
    'COMPARC1': 'Financieras',
    'CONCESI1': 'Fondos de Inversión',
    'COP': 'Energía',
    'COPECUS': 'Otros (internacional)',
    'COPENC1': 'Diversas',
    'COPX': 'ETF internacional',
    'CORAREC1': 'Industriales',
    'CORAREI1': 'Industriales',
    'CORFICUS': 'Financiero',
    'COST': 'Consumo básico',
    'COWZ': 'ETF internacional',
    'CPAC': 'Holdings / ADR',
    'CPACASC1': 'Industriales',
    'CPACASI1': 'Industriales',
    'CQQQ': 'ETF internacional',
    'CRANDEC1': 'Financieras',
    'CRECAPC1': 'Financieras',
    'CRECERC1': 'Seguros',
    'CREDITC1': 'Financieras',
    'CRETEXC1': 'Industriales',
    'CRETEXI1': 'Industriales',
    'CRM': 'Tecnología',
    'CRPA': 'ETF internacional',
    'CRPU': 'ETF internacional',
    'CRWD': 'Tecnología',
    'CSCO': 'Tecnología',
    'CSKRUS': 'ETF internacional',
    'CSPX': 'ETF internacional',
    'CTOROUS': 'Otros (internacional)',
    'CUMBRAC1': 'Industriales',
    'CUSS': 'ETF internacional',
    'CVERDEC1': 'Mineras',
    'CVS': 'Salud',
    'CVX': 'Energía',
    'D26A': 'ETF internacional',
    'D28A': 'ETF internacional',
    'DAL': 'Otros (internacional)',
    'DAPP': 'ETF internacional',
    'DBEFUS': 'ETF internacional',
    'DBEU': 'ETF internacional',
    'DEFSUS': 'ETF internacional',
    'DELL': 'Tecnología',
    'DESXXIC1': 'Diversas',
    'DGCB': 'ETF internacional',
    'DIA': 'ETF internacional',
    'DIS': 'Comunicaciones',
    'DPST': 'ETF internacional',
    'DRAMUS': 'ETF internacional',
    'DTCR': 'ETF internacional',
    'DTLA': 'ETF internacional',
    'DUNENC1': 'Diversas',
    'DUST': 'ETF internacional',
    'DXJ': 'ETF internacional',
    'ECH': 'ETF internacional',
    'ECLUS': 'Otros (internacional)',
    'ECOPETUS': 'Energía',
    'ECU': 'Mineras',
    'EDUNASC1': 'Servicios Públicos',
    'EEM': 'ETF internacional',
    'EFA': 'ETF internacional',
    'EFECTIC1': 'Financieras',
    'EGEPIBC1': 'Servicios Públicos',
    'EGESUBC1': 'Servicios Públicos',
    'EIMI': 'ETF internacional',
    'EIMU': 'ETF internacional',
    'ELCOMEI1': 'Industriales',
    'ELECPBC1': 'Servicios Públicos',
    'ELESUDC1': 'Servicios Públicos',
    'EMB': 'ETF internacional',
    'EMCA': 'ETF internacional',
    'EMCR': 'ETF internacional',
    'EMGA': 'ETF internacional',
    'EMLCUS': 'ETF internacional',
    'EMXCUS': 'ETF internacional',
    'ENELAMUS': 'Otros (internacional)',
    'ENELCLUS': 'Otros (internacional)',
    'ENGIEC1': 'Servicios Públicos',
    'ENPACIC1': 'Servicios Públicos',
    'ENPACII1': 'Fondos de Inversión',
    'ENPH': 'Energía',
    'ENTELUS': 'Comunicaciones',
    'EPI': 'ETF internacional',
    'EPU': 'ETF internacional',
    'EPUNOBC1': 'Servicios Públicos',
    'EQACUS': 'ETF internacional',
    'ESGV': 'ETF internacional',
    'ESUREBC1': 'Servicios Públicos',
    'ETERNII1': 'Industriales',
    'ETHA': 'ETF internacional',
    'ETHU': 'ETF internacional',
    'ETN': 'Otros (internacional)',
    'ETNAI1': 'Industriales',
    'EUFN': 'ETF internacional',
    'EWG': 'ETF internacional',
    'EWJ': 'ETF internacional',
    'EWY': 'ETF internacional',
    'EWZ': 'ETF internacional',
    'EXALMC1': 'Industriales',
    'EXCHUS': 'ETF internacional',
    'EXITOUS': 'Consumo discrecional',
    'EXPERTC1': 'Diversas',
    'EZU': 'ETF internacional',
    'F': 'Consumo discrecional',
    'FALABEUS': 'Otros (internacional)',
    'FANUPEC1': 'Agrario',
    'FAS': 'ETF internacional',
    'FCONFIC1': 'Financieras',
    'FCREDIC1': 'Financieras',
    'FCX': 'Otros (internacional)',
    'FDX': 'Industrial',
    'FEGE': 'ETF internacional',
    'FERREYC1': 'Industriales',
    'FEZ': 'ETF internacional',
    'FIBCCAP': 'FIBRA / Inmobiliario',
    'FIBPRIME': 'FIBRA / Inmobiliario',
    'FILAMEI1': 'Fondos de Inversión',
    'FINTFCC1': 'Financieras',
    'FLGV': 'ETF internacional',
    'FLHY': 'ETF internacional',
    'FLIN': 'ETF internacional',
    'FLXIUS': 'ETF internacional',
    'FOSPACC1': 'Mineras',
    'FOSSALC1': 'Materiales',
    'FOSSALI1': 'Fondos de Inversión',
    'FPROEMC1': 'Financieras',
    'FPROEMP1': 'Financieras',
    'FTLS': 'ETF internacional',
    'FUTURAC1': 'Diversas',
    'FUTURAI1': 'Fondos de Inversión',
    'FXI': 'ETF internacional',
    'GANSALC1': 'Agrario',
    'GARGOSUS': 'Otros (internacional)',
    'GBOLIVUS': 'Otros (internacional)',
    'GBVLAC1': 'Financieras',
    'GBVLBC1': 'Financieras',
    'GDX': 'ETF internacional',
    'GDX1': 'ETF internacional',
    'GDXJ': 'ETF internacional',
    'GE': 'Industrial',
    'GEBUS': 'Otros (internacional)',
    'GGLL': 'ETF internacional',
    'GILD': 'Salud',
    'GLD': 'ETF internacional',
    'GLDM': 'ETF internacional',
    'GLORIAI1': 'Industriales',
    'GM': 'Consumo discrecional',
    'GNBC1': 'Financieras',
    'GNBC2': 'Financieras',
    'GOAU': 'ETF internacional',
    'GOOG': 'Comunicaciones',
    'GOOGL': 'Comunicaciones',
    'GRHOLDC1': 'Inmobiliario',
    'GRID': 'ETF internacional',
    'GRSURAUS': 'Otros (internacional)',
    'GS': 'Financiero',
    'HABITAC1': 'AFP',
    'HBM': 'Materiales',
    'HD': 'Consumo discrecional',
    'HDV': 'ETF internacional',
    'HEAL': 'ETF internacional',
    'HEDJ': 'ETF internacional',
    'HERMESC1': 'Industriales',
    'HIDRA2C1': 'Servicios Públicos',
    'HIDROSI1': 'Industriales',
    'HODL': 'ETF internacional',
    'HOOD': 'Otros (internacional)',
    'HPE': 'Otros (internacional)',
    'HYBL': 'ETF internacional',
    'HYEM': 'ETF internacional',
    'HYG': 'ETF internacional',
    'HYLA': 'ETF internacional',
    'HYLD': 'ETF internacional',
    'HYLHUS': 'ETF internacional',
    'I500': 'ETF internacional',
    'IAMUS': 'Otros (internacional)',
    'IAU': 'ETF internacional',
    'IB01': 'ETF internacional',
    'IBB': 'ETF internacional',
    'IBDZ': 'ETF internacional',
    'IBHIUS': 'ETF internacional',
    'IBIT': 'ETF internacional',
    'IBKR': 'Otros (internacional)',
    'IBM': 'Tecnología',
    'IBTA': 'ETF internacional',
    'ICBCC1': 'Financieras',
    'ICLO1': 'ETF internacional',
    'ID27': 'ETF internacional',
    'ID29': 'ETF internacional',
    'ID30': 'ETF internacional',
    'ID31US': 'ETF internacional',
    'ID32': 'ETF internacional',
    'ID34': 'ETF internacional',
    'IDTM': 'ETF internacional',
    'IDTP': 'ETF internacional',
    'IEF': 'ETF internacional',
    'IEFA': 'ETF internacional',
    'IEMB': 'ETF internacional',
    'IEMG': 'ETF internacional',
    'IEQSAI1': 'Industriales',
    'IEUS': 'ETF internacional',
    'IFS': 'Holdings / ADR',
    'IGLA': 'ETF internacional',
    'IGM': 'ETF internacional',
    'IGSB': 'ETF internacional',
    'IGV': 'ETF internacional',
    'IHI': 'ETF internacional',
    'IHYA': 'ETF internacional',
    'IHYU': 'ETF internacional',
    'IIDEC1': 'Diversas',
    'IIDEI1': 'Fondos de Inversión',
    'IJPD': 'ETF internacional',
    'IJR': 'ETF internacional',
    'ILCUS': 'Otros (internacional)',
    'ILF': 'ETF internacional',
    'IMBA': 'ETF internacional',
    'INCM': 'ETF internacional',
    'INCRAIC1': 'Diversas',
    'INDA': 'ETF internacional',
    'INDECOI1': 'Industriales',
    'INFIXPC1': 'Financieras',
    'INRETC1': 'Holdings / ADR',
    'INSURC1': 'Seguros',
    'INTC': 'Tecnología',
    'INTEGRC1': 'AFP',
    'INTERBC1': 'Financieras',
    'INTPEBC1': 'Servicios Públicos',
    'INTPECC1': 'Servicios Públicos',
    'INTSEGC1': 'Seguros',
    'INVCENC1': 'Inmobiliario',
    'INVCO2C1': 'Diversas',
    'INVCORI1': 'Fondos de Inversión',
    'INVERPC1': 'Diversas',
    'INVERTC1': 'Diversas',
    'INVFALC1': 'Financieras',
    'IOO': 'ETF internacional',
    'IPCHAC1': 'Industriales',
    'IPCHBC1': 'Industriales',
    'IQLT': 'ETF internacional',
    'ISAC': 'ETF internacional',
    'ISAUS': 'Otros (internacional)',
    'ISEU': 'ETF internacional',
    'ISICC1': 'Inmobiliario',
    'ITAUCLUS': 'Otros (internacional)',
    'ITAUS': 'ETF internacional',
    'IU28': 'ETF internacional',
    'IU29US': 'ETF internacional',
    'IUAA': 'ETF internacional',
    'IUAG': 'ETF internacional',
    'IUFS': 'ETF internacional',
    'IUIT': 'ETF internacional',
    'IUQA': 'ETF internacional',
    'IUQD': 'ETF internacional',
    'IUSG': 'ETF internacional',
    'IUVD': 'ETF internacional',
    'IUVL': 'ETF internacional',
    'IVE': 'ETF internacional',
    'IVV': 'ETF internacional',
    'IVVM': 'ETF internacional',
    'IWF': 'ETF internacional',
    'IWM': 'ETF internacional',
    'IWO': 'ETF internacional',
    'IWQU': 'ETF internacional',
    'IYR': 'ETF internacional',
    'IYW': 'ETF internacional',
    'JAAA': 'ETF internacional',
    'JAAA1': 'ETF internacional',
    'JEIA': 'ETF internacional',
    'JEPG': 'ETF internacional',
    'JEPI': 'ETF internacional',
    'JEPQ': 'ETF internacional',
    'JETS': 'ETF internacional',
    'JNJ': 'Salud',
    'JNUG': 'ETF internacional',
    'JPEA': 'ETF internacional',
    'JPM': 'Financiero',
    'JPMORGC1': 'Diversas',
    'JREG': 'ETF internacional',
    'JREU': 'ETF internacional',
    'K': 'Materiales',
    'KHC': 'Consumo básico',
    'KO': 'Consumo básico',
    'KOLD': 'ETF internacional',
    'KRE': 'ETF internacional',
    'KWEB': 'ETF internacional',
    'LABU': 'ETF internacional',
    'LAIVEBC1': 'Industriales',
    'LAREDOC1': 'Agrario',
    'LIBSEGC1': 'Seguros',
    'LIT': 'ETF internacional',
    'LLY': 'Salud',
    'LMT': 'Industrial',
    'LQD': 'ETF internacional',
    'LQDA': 'ETF internacional',
    'LQDE': 'ETF internacional',
    'LTMUS': 'Consumo discrecional',
    'LUISAI1': 'Mineras',
    'LUSURC1': 'Servicios Públicos',
    'MA': 'Financiero',
    'MAGS': 'ETF internacional',
    'MALLPLUS': 'Otros (internacional)',
    'MAPFSGC1': 'Seguros',
    'MCD': 'Consumo discrecional',
    'MCHI': 'ETF internacional',
    'MELI': 'Consumo discrecional',
    'META': 'Comunicaciones',
    'METU': 'ETF internacional',
    'MGK': 'ETF internacional',
    'MIBANC1': 'Financieras',
    'MICHEI1': 'Industriales',
    'MINCORC1': 'Mineras',
    'MINCORI1': 'Mineras',
    'MINEROUS': 'Otros (internacional)',
    'MINSURI1': 'Mineras',
    'MIRL': 'Mineras',
    'MITSUFC1': 'Financieras',
    'MMM': 'Industrial',
    'MOAT': 'ETF internacional',
    'MOROCOC1': 'Mineras',
    'MOROCOI1': 'Mineras',
    'MRK': 'Salud',
    'MRNA': 'Otros (internacional)',
    'MS': 'Financiero',
    'MSFT': 'Tecnología',
    'MSFU': 'ETF internacional',
    'MSTR': 'Tecnología',
    'MU': 'Tecnología',
    'MUU': 'ETF internacional',
    'N100': 'ETF internacional',
    'NACSEGC1': 'Seguros',
    'NDIA': 'ETF internacional',
    'NEE': 'Energía',
    'NEM': 'Otros (internacional)',
    'NEXAPEC1': 'Mineras',
    'NEXAPEI1': 'Mineras',
    'NFLX': 'Comunicaciones',
    'NFXL': 'ETF internacional',
    'NKE': 'Consumo discrecional',
    'NLR': 'ETF internacional',
    'NOBL': 'ETF internacional',
    'NOWUS': 'Otros (internacional)',
    'NUAM': 'Holdings / ADR',
    'NUGT': 'ETF internacional',
    'NVDA': 'Tecnología',
    'NVDL': 'ETF internacional',
    'ON': 'Tecnología',
    'ORCL': 'Tecnología',
    'ORCX': 'ETF internacional',
    'ORYGENC1': 'Servicios Públicos',
    'OXY': 'Energía',
    'PACIFIC1': 'Seguros',
    'PALOALC1': 'Diversas',
    'PANW': 'Tecnología',
    'PARAMOC1': 'Agrario',
    'PARAUCUS': 'Otros (internacional)',
    'PAVE': 'ETF internacional',
    'PAVE1US': 'ETF internacional',
    'PDD': 'Consumo discrecional',
    'PEIUS': 'Consumo discrecional',
    'PEP': 'Consumo básico',
    'PERENAC1': 'Servicios Públicos',
    'PERENBC1': 'Servicios Públicos',
    'PETROBC1': 'Industriales',
    'PFAVALUS': 'Otros (internacional)',
    'PFCIBEUS': 'Otros (internacional)',
    'PFCORFUS': 'Financiero',
    'PFDAVIUS': 'Otros (internacional)',
    'PFE': 'Salud',
    'PFGARGUS': 'Otros (internacional)',
    'PFSURAUS': 'Otros (internacional)',
    'PG': 'Consumo básico',
    'PGHYUS': 'ETF internacional',
    'PHTBC1': 'Inmobiliario',
    'PIURAC1': 'Industriales',
    'PIURAI1': 'Industriales',
    'PLTR': 'Tecnología',
    'PLTU': 'ETF internacional',
    'PLUZENC1': 'Servicios Públicos',
    'PML': 'Mineras',
    'PODERC1': 'Mineras',
    'POMALCC1': 'Agrario',
    'PORTAC1': 'Inmobiliario',
    'POSITIC1': 'Seguros',
    'POSITVC1': 'Seguros',
    'PPX': 'Mineras',
    'PRIMAC1': 'AFP',
    'PROFUTC1': 'AFP',
    'PROMIGUS': 'Energía',
    'PROTECC1': 'Seguros',
    'PSIUS': 'ETF internacional',
    'PSKY': 'Otros (internacional)',
    'PUCALAC1': 'Agrario',
    'PVTBC1': 'Diversas',
    'PYPL': 'Financiero',
    'QAPAQC1': 'Financieras',
    'QCOM': 'Tecnología',
    'QGRW': 'ETF internacional',
    'QGRW1': 'ETF internacional',
    'QQQ': 'ETF internacional',
    'QQQM': 'ETF internacional',
    'QTUM': 'ETF internacional',
    'QUAL': 'ETF internacional',
    'QUALSGC1': 'Seguros',
    'QUIMPAC1': 'Industriales',
    'QUIMPAI1': 'Industriales',
    'QUINENUS': 'Otros (internacional)',
    'QYLD': 'ETF internacional',
    'R1GR': 'ETF internacional',
    'R2US': 'ETF internacional',
    'RBCAC1': 'Diversas',
    'RBCBC1': 'Financieras',
    'RECORDI1': 'Industriales',
    'REG': 'Mineras',
    'REGN': 'Salud',
    'REMX': 'ETF internacional',
    'RIMSEGC1': 'Seguros',
    'RIO': 'Mineras',
    'RIPLEYUS': 'Otros (internacional)',
    'RSP': 'ETF internacional',
    'RVIA5BC1': 'Industriales',
    'RYLD': 'ETF internacional',
    'SAGAC1': 'Consumo Discrecional',
    'SALFACUS': 'Otros (internacional)',
    'SANC1': 'Financieras',
    'SANFINC1': 'Financieras',
    'SANGABC1': 'Servicios Públicos',
    'SANTCOC1': 'Financieras',
    'SBUX': 'Consumo discrecional',
    'SCCO': 'Mineras',
    'SCHD': 'ETF internacional',
    'SCOTIAC1': 'Financieras',
    'SDHA': 'ETF internacional',
    'SDIA': 'ETF internacional',
    'SDIG': 'ETF internacional',
    'SDVY': 'ETF internacional',
    'SEA': 'ETF internacional',
    'SEALDC1': 'Servicios Públicos',
    'SEDAPBC1': 'Servicios Públicos',
    'SGDJ': 'ETF internacional',
    'SHLD': 'ETF internacional',
    'SHOP': 'Otros (internacional)',
    'SHOUGEC1': 'Servicios Públicos',
    'SHPC1': 'Mineras',
    'SHY': 'ETF internacional',
    'SIDERC1': 'Industriales',
    'SIL': 'ETF internacional',
    'SILJ': 'ETF internacional',
    'SLB': 'Energía',
    'SLON': 'Otros (internacional)',
    'SLV': 'ETF internacional',
    'SLVR': 'ETF internacional',
    'SMCI': 'Tecnología',
    'SMH': 'ETF internacional',
    'SMIN': 'ETF internacional',
    'SMT/UK': 'ETF internacional',
    'SMUUS': 'Otros (internacional)',
    'SNCRISC1': 'Industriales',
    'SNDKUS': 'Otros (internacional)',
    'SNJACIC1': 'Agrario',
    'SNJUANC1': 'Industriales',
    'SNJUANI1': 'Industriales',
    'SOLUCIC1': 'Diversas',
    'SOXL': 'ETF internacional',
    'SOXX': 'ETF internacional',
    'SPCCPI1': 'Mineras',
    'SPCCPI2': 'Mineras',
    'SPCXUS': 'Tecnología',
    'SPEQ': 'ETF internacional',
    'SPGIUS': 'Otros (internacional)',
    'SPGP': 'ETF internacional',
    'SPHQ': 'ETF internacional',
    'SPMOUS': 'ETF internacional',
    'SPSM': 'ETF internacional',
    'SPXL': 'ETF internacional',
    'SPY': 'ETF internacional',
    'SPYG': 'ETF internacional',
    'SPYI': 'ETF internacional',
    'SPYL': 'ETF internacional',
    'SPYM': 'ETF internacional',
    'SQMBUS': 'Otros (internacional)',
    'SQQQ': 'ETF internacional',
    'SRET': 'ETF internacional',
    'SRLN': 'ETF internacional',
    'SSO': 'ETF internacional',
    'STG': 'Holdings / ADR',
    'STXUS': 'Financiero',
    'STYC': 'ETF internacional',
    'STZ': 'Otros (internacional)',
    'T': 'Comunicaciones',
    'TECL': 'ETF internacional',
    'TEF': 'Holdings / ADR',
    'TELCAAC1': 'Servicios Públicos',
    'TELCABC1': 'Servicios Públicos',
    'TERPELUS': 'Otros (internacional)',
    'TFLOUS': 'ETF internacional',
    'TGT': 'Otros (internacional)',
    'TI5A': 'ETF internacional',
    'TIP': 'ETF internacional',
    'TLH': 'ETF internacional',
    'TLT': 'ETF internacional',
    'TLTW': 'ETF internacional',
    'TMF': 'ETF internacional',
    'TMO': 'Salud',
    'TMUS': 'Comunicaciones',
    'TOTALSC1': 'Financieras',
    'TQQQ': 'ETF internacional',
    'TRADIC1': 'Diversas',
    'TSLA': 'Consumo discrecional',
    'TSLL': 'ETF internacional',
    'TSMUS': 'Tecnología',
    'TTD': 'Otros (internacional)',
    'TUMANC1': 'Agrario',
    'UAE': 'ETF internacional',
    'UAL': 'Financiero',
    'UBER': 'Industrial',
    'UCO': 'ETF internacional',
    'UDVD': 'ETF internacional',
    'UNACEMC1': 'Materiales',
    'UNH': 'Salud',
    'UNITEXC1': 'Industriales',
    'UNITEXI1': 'Industriales',
    'UPRO': 'ETF internacional',
    'UPS': 'Industrial',
    'URA': 'ETF internacional',
    'USC5US': 'ETF internacional',
    'USD1': 'ETF internacional',
    'USMV': 'ETF internacional',
    'USO': 'ETF internacional',
    'UUP': 'ETF internacional',
    'V': 'Financiero',
    'VAPOREUS': 'Otros (internacional)',
    'VB': 'ETF internacional',
    'VBRUS': 'ETF internacional',
    'VCIT': 'ETF internacional',
    'VDPA': 'ETF internacional',
    'VDSTUS': 'ETF internacional',
    'VDTA': 'ETF internacional',
    'VEA': 'ETF internacional',
    'VFEAUS': 'ETF internacional',
    'VGK': 'ETF internacional',
    'VGT': 'ETF internacional',
    'VHYA': 'ETF internacional',
    'VIVSEGC1': 'Seguros',
    'VJPU': 'ETF internacional',
    'VNLA': 'ETF internacional',
    'VOLCAAC1': 'Mineras',
    'VOLCABC1': 'Mineras',
    'VOO': 'ETF internacional',
    'VT': 'ETF internacional',
    'VTI': 'ETF internacional',
    'VTV': 'ETF internacional',
    'VUAA': 'ETF internacional',
    'VUGUS': 'ETF internacional',
    'VWO': 'ETF internacional',
    'VWRA': 'ETF internacional',
    'VXUS': 'ETF internacional',
    'VZ': 'Comunicaciones',
    'WDEFUS': 'ETF internacional',
    'WFC': 'Financiero',
    'WIAU': 'ETF internacional',
    'WMT': 'Consumo básico',
    'WPM': 'Otros (internacional)',
    'XAR': 'ETF internacional',
    'XBI': 'ETF internacional',
    'XEOU': 'ETF internacional',
    'XLC': 'ETF internacional',
    'XLE': 'ETF internacional',
    'XLF': 'ETF internacional',
    'XLI': 'ETF internacional',
    'XLK': 'ETF internacional',
    'XLP': 'ETF internacional',
    'XLRE': 'ETF internacional',
    'XLU': 'ETF internacional',
    'XLV': 'ETF internacional',
    'XLY': 'ETF internacional',
    'XMED': 'ETF internacional',
    'XNTK': 'ETF internacional',
    'XOM': 'Energía',
    'XYLD': 'ETF internacional',
    'XYZ': 'Otros (internacional)',
    'YINN': 'ETF internacional',
    'ZAP': 'ETF internacional',
    'ZM': 'Comunicaciones',
    'ZTS': 'Otros (internacional)',
}

# Nombres completos (solo los que se conocen)
BVL_NAMES = {
    'AAL': 'American Airlines Group Inc',
    'AAPL': 'Apple Inc',
    'AAPU': 'Direxion Daily Aapl Bull 2X Shares',
    'ABNB': 'Airbnb, Inc.',
    'ABT': 'Abbott Laboratories',
    'ABX': 'Barrick Mining Corporation',
    'ACNUS': 'Accenture Plc',
    'ACWDUS': 'State Street Spdr Msci All Country World Ucits Etf Usd (Acc)',
    'ACWI': 'Ishares Msci Acwi Etf',
    'ACWX': 'Ishares Msci Acwi Ex U.S. Etf',
    'ADBE': 'Adobe Inc.',
    'ADI': 'Analog Devices, Inc.',
    'AEM': 'Agnico Eagle Mines Limited',
    'AGG': 'Ishares Core U.S. Aggregate Bond Etf',
    'AGGG': 'iShares Core Global Aggregate Bond UCITS ETF USD (DIST)',
    'AGGU': 'iShares Core Global Aggregate Bond UCITS ETF USD Hedged (ACC)',
    'AGIXUS': 'Kraneshares Public-Private Ai & Technology Etf',
    'AGUASAUS': 'Aguas Andinas S.A.',
    'AIQ': 'Global X Artificial Intelligence & Technology Etf',
    'AMAT': 'Applied Materials, Inc.',
    'AMD': 'Advanced Micro Devices, Inc.',
    'AMUU': 'Direxion Daily AMD Bull 2X Shares',
    'AMZN': 'Amazon.Com Inc.',
    'AMZU': 'Direxion Daily Amzn Bull 2X Shares',
    'ANDINBUS': 'Embotelladora Andina S.A.',
    'ANETUS': 'Arista Networks, Inc.',
    'APOUS': 'Apollo Global Management, Inc',
    'APP': 'Applovin Corporation',
    'ARGT': 'Global X MSCI Argentina ETF',
    'ARKF': 'ARK Blockchain & Fintech Innovation ETF',
    'ARKG': 'Ark Genomic Revolution Etf',
    'ARKK': 'Ark Innovation Etf',
    'ARKQ': 'Ark Autonomous Technology & Robotics Etf',
    'ARKW': 'Ark Next Generation Technology Etf',
    'ARKX': 'ARK Space & Defense Innovation ETF',
    'ASML': 'Asml Holding Nv',
    'AVGO': 'Broadcom Inc.',
    'AVL': 'Direxion Daily Avgo Bull 2X Etf',
    'AXP': 'American Express Co',
    'BA': 'The Boeing Company',
    'BABAUS': 'Alibaba Group Holding Limited',
    'BAC': 'Bank Of America Corporation',
    'BAI': 'iShares A.I. Innovation and Tech Active ETF',
    'BBVA': 'Banco Bilbao Vizcaya Argentaria S.A.',
    'BCIUS': 'Banco De Crédito E Inversiones',
    'BIDU': 'Baidu Inc',
    'BITO': 'Proshares Bitcoin Etf',
    'BITU': 'Proshares Ultra Bitcoin Etf',
    'BITX': '2X Bitcoin ETF',
    'BKLN': 'Invesco Senior Loan Etf',
    'BKNG': 'Booking Holdings Inc.',
    'BLK': 'Blackrock, Inc.',
    'BLTN': 'iShares Brazil LTN BRL Govt Bond UCITS ETF (DE)',
    'BMY': 'Bristol-Myers Squibb Company',
    'BNDW': 'Vanguard Total World Bond Etf',
    'BOGOTAUS': 'Banco De Bogota S.A.',
    'BOIL': 'Proshares Ultra Bloomberg Natural Gas',
    'BOTZ': 'Global X Robotics & Artificial Intelligence Etf',
    'BRK/B': 'Berkshire Hathaway Inc.',
    'BRZU': 'Direxion Daily Msci Brazil Bull 2X Shares',
    'BS0A': 'Invesco Bulletshares 2030 Usd Corporate Bond Ucits Etf Acc',
    'BS28': 'Invesco Bulletshares 2028 Usd Corporate Bond Ucits Etf Dist',
    'BS29': 'Invesco Bulletshares 2029 Usd Corporate Bond Ucits Etf Dist',
    'BS30': 'Invesco Bulletshares 2030 Usd Corporate Bond Ucits Etf Dist',
    'BS8A': 'Invesco Bulletshares 2028 Usd Corporate Bond Ucits Etf Acc',
    'BS9A': 'Invesco Bulletshares 2029 Usd Corporate Bond Ucits Etf Acc',
    'BSANTAUS': 'Banco Santander-Chile',
    'BTCCU': 'Purpose Bitcoin Etf',
    'BTCO': 'Invesco Galaxy Bitcoin Etf',
    'BUG': 'Global X Cybersecurity Etf',
    'C': 'Citigroup Inc.',
    'CAPUS': 'Cap S.A.',
    'CAT': 'Caterpillar Inc.',
    'CBU0': 'Ishares Vii Plc Ishrs Trsry Bond 7-10Yr Etf Usd (Acc)',
    'CBU7': 'Ishares Usd Treasury Bond 3-7 Yr Ucits Etf',
    'CCL': 'Carnival Corporation',
    'CCOUS': 'Cameco Corporation',
    'CCUUS': 'Compañía Cervecerías Unidas S.A.',
    'CELSIAUS': 'Celsia S.A.',
    'CEMARGUS': 'Cementos Argos S.A.',
    'CEMB': 'iShares J.P. Morgan EM Corporate Bond ETF',
    'CENCOSUS': 'Cencosud S.A.',
    'CENMALUS': 'Cencosud Shopping S.A.',
    'CHILEUS': 'Banco De Chile',
    'CIBESTUS': 'Grupo Cibest S.A.',
    'CIBR': 'First Trust Nasdaq Cybersecurity Etf',
    'CIBR1US': 'First Trust Nasdaq Cybersecurity UCITS ETF - Acc (USD)',
    'CIND': 'Ishares Dow Jones Industrial Average Ucits Etf Usd (Acc)',
    'CJPU': 'Ishares Msci Japan Ucits Etf Usd (Acc)',
    'CMG': 'Chipotle Mexican Grill Inc.',
    'CMPCUS': 'Empresas Cmpc S.A.',
    'CNDX': 'Ishares Nasdaq 100 Ucits Etf',
    'COIN': 'Coinbase Global, Inc.',
    'COLBUNUS': 'Colbún S.A.',
    'COP': 'ConocoPhillips',
    'COPECUS': 'Empresas Copec S.A.',
    'COPX': 'Global X Copper Miners Etf',
    'CORFICUS': 'Corporación Financiera Colombiana S.A.',
    'COST': 'Costco Wholesale Corporation',
    'COWZ': 'Pacer Us Cash Cows 100 Etf',
    'CQQQ': 'Invesco China Technology Etf',
    'CRM': 'Salesforce.Com, Inc',
    'CRPA': 'iShares Global Corp Bond UCITS ETF USD ACC',
    'CRPU': 'iShares Global Corp Bond UCITS ETF USD (ACC)',
    'CRWD': 'Crowdstrike Holdings, Inc.',
    'CSCO': 'Cisco Systems, Inc',
    'CSKRUS': 'Ishares Msci Korea Ucits Etf Usd (Acc)',
    'CSPX': 'Ishares Vii Plc Ishrs Core S&P 500 Ucits Etf Usd (Acc)',
    'CTOROUS': 'Viña Concha Y Toro S.A.',
    'CUSS': 'iShares MSCI USA Small Cap ESG Enhanced UCITS ETF',
    'CVS': 'Cvs Health Corporation',
    'CVX': 'Chevron Corporation',
    'D26A': 'iShares iBonds Dec 2026 Term $ Corp UCITS ETF',
    'D28A': 'iShares iBonds Dec 2028 Term $ Corp UCITS ETF',
    'DAL': 'Delta Air Lines, Inc.',
    'DAPP': 'VANECK DIGITAL TRANSFORMATION ETF (antes VANECK VECTORS DIGITAL TRANSFORMATION ETF)',
    'DBEFUS': 'Xtrackers Msci Eafe Hedged Equity Etf',
    'DBEU': 'Xtrackers Msci Europe Hedged Equity Etf',
    'DEFSUS': 'Amundi Stoxx Europe Defense Ucits Etf Acc',
    'DELL': 'Dell Technologies Inc.',
    'DGCB': 'Dimensional Global Credit Etf',
    'DIA': 'Spdr Dow Jones Industrial Average Etf',
    'DIS': 'The Walt Disney Com',
    'DPST': 'Direxion Daily Regional Banks Bull 3X Shares',
    'DRAMUS': 'Roundhill Memory ETF',
    'DTCR': 'Global X Data Center & Digital Infrastructure Etf',
    'DTLA': 'iShares $ Treasury Bond 20+yr UCITS ETF',
    'DUST': 'Direxion Daily Gold Miners Index Bear 2X Shares',
    'DXJ': 'Wisdomtree Japan Hedged Equity Fund',
    'ECH': 'Ishares Msci Chile Etf',
    'ECLUS': 'Engie Energía Chile S.A.',
    'ECOPETUS': 'Ecopetrol S.A.',
    'EEM': 'Ishares Msci Emerging Markets Etf',
    'EFA': 'Ishares Msci Eafe Etf',
    'EIMI': 'Ishares Core Msci Em Imi Ucits Etf',
    'EIMU': 'iShares Core MSCI EM IMI UCITS ETF USD (DIST)',
    'EMB': 'Ishares J.P. Morgan Usd Emerging Markets Bond Etf',
    'EMCA': 'Ishares J.P. Morgan $ Em Corp Bond Ucits Etf',
    'EMCR': 'Ishares J.P. Morgan $ Em Corp Bond Ucits Etf Usd (Dist)',
    'EMGA': 'Ishares J.P. Morgan Em Local Govt Bond Ucits Etf (Acc)',
    'EMLCUS': 'VANECK J.P. MORGAN EM LOCAL CURRENCY BOND ETF (antes VANECK VECTORS J.P. MORGAN EM LOCAL CURRENCY BOND ETF)',
    'EMXCUS': 'iShares MSCI Emerging Markets ex China ETF',
    'ENELAMUS': 'Enel Americas S.A.',
    'ENELCLUS': 'Enel Chile S.A.',
    'ENPH': 'Enphase Energy, Inc.',
    'ENTELUS': 'Empresa Nacional De Telecomunicaciones S.A.',
    'EPI': 'WisdomTree India Earnings Fund',
    'EPU': 'Ish Msci Peru And Glob Exp Etf',
    'EQACUS': 'Invesco Eqqq Nasdaq-100 Ucits Etf Acc',
    'ESGV': 'Vanguard Esg U.S. Stock Etf',
    'ETHA': 'Ishares Ethereum Trust Etf',
    'ETHU': '2x Ether ETF',
    'ETN': 'Eaton Corporation Plc',
    'EUFN': 'Ishares Msci Europe Financials Etf',
    'EWG': 'Ishares Msci Germany Etf',
    'EWJ': 'Ishares Msci Japan Etf',
    'EWY': 'iShares MSCI South Korea ETF',
    'EWZ': 'Ishares Msci Brazil Capped Etf',
    'EXCHUS': 'Ishares Msci Em Ex-China Ucits Etf Usd Acc',
    'EXITOUS': 'Almacenes Éxito S.A.',
    'EZU': 'Ishares Msci Eurozone Etf',
    'F': 'Ford Motor Company',
    'FALABEUS': 'Falabella S.A.',
    'FAS': 'Direxion Daily Financial Bull 3X Shares',
    'FCX': 'Freeport Mcmoran Inc',
    'FDX': 'Fedex Corporation',
    'FEGE': 'First Eagle Global Equity Etf',
    'FEZ': 'State Street Spdr Euro Stoxx 50 Etf',
    'FLGV': 'Franklin U.S. Treasury Bond ETF',
    'FLHY': 'Franklin High Yield Corporate ETF',
    'FLIN': 'Franklin FTSE India ETF',
    'FLXIUS': 'Franklin FTSE India UCITS ETF',
    'FTLS': 'First Trust Long/Short Equity Etf',
    'FXI': 'Ishares China Large - Cap Etf',
    'GARGOSUS': 'Grupo Argos S.A.',
    'GBOLIVUS': 'Grupo Bolivar S.A.',
    'GDX': 'Vaneck Gold Miners Etf',
    'GDX1': 'Vaneck Gold Miners Ucits Etf',
    'GDXJ': 'Vaneck Junior Gold Miners Etf',
    'GE': 'General Electric Company',
    'GEBUS': 'Grupo Energia Bogota S.A. E.S.P.',
    'GGLL': 'Direxion Daily GOOGL Bull 2X Shares',
    'GILD': 'Gilead Sciences, Inc.',
    'GLD': 'Spdr Gold Trust Spdr Gold Shares',
    'GLDM': 'SPDR Gold MiniShares Trust',
    'GM': 'General Motors Company',
    'GOAU': 'U.S. Global GO GOLD and Precious Metal Miners ETF',
    'GOOG': 'Alphabet Inc.',
    'GOOGL': 'Alphabet Inc.',
    'GRID': 'First Trust Nasdaq Clean Edge Smart Grid Infrastructure Index Fund',
    'GRSURAUS': 'Grupo De Inversiones Suramericana S.A.',
    'GS': 'Goldman Sachs Group, Inc.',
    'HBM': 'Hudbay Minerals Inc.',
    'HD': 'The Home Depot, Inc.',
    'HDV': 'Ishares Core High Dividend Etf',
    'HEAL': 'Global X HealthTech ETF',
    'HEDJ': 'Wisdomtree Europe Hedged Equity Fund',
    'HODL': 'Vaneck Bitcoin Trust',
    'HOOD': 'Robinhood Markets, Inc.',
    'HPE': 'Hewlett Packard Enterprise Company',
    'HYBL': 'State Street Blackstone High Income ETF',
    'HYEM': 'Vaneck Emerging Markets High Yield Bond Etf',
    'HYG': 'Ishares Iboxx $ High Yield Corporate Bond Etf',
    'HYLA': 'iShares Global High Yield Corp Bond UCITS ETF USD (ACC)',
    'HYLD': 'iShares Global High Yield Corp Bond UCITS ETF USD (DIST)',
    'HYLHUS': 'Ishares Global High Yield Corp Bond Ucits Etf',
    'I500': 'Ishares S&P 500 Swap Ucits Etf Usd (Acc)',
    'IAMUS': 'Inversiones Aguas Metropolitanas S.A.',
    'IAU': 'Ishares Gold Trust',
    'IB01': 'Ishares $ Treasury Bond 0-1Yr Ucits Etf Usd (Acc)',
    'IBB': 'Ishares Biotechnology Etf',
    'IBDZ': 'iShares iBonds Dec 2034 Term Corporate ETF',
    'IBHIUS': 'iShares iBonds 2029 Term High Yield and Income ETF',
    'IBIT': 'iShares Bitcoin Trust',
    'IBKR': 'Interactive Brokers Group, Inc.',
    'IBM': 'International Business Machine',
    'IBTA': 'Ishares $ Treasury Bond 1-3Yr Ucits Etf',
    'ICLO1': 'Invesco USD AAA CLO UCITS ETF DIST',
    'ID27': 'iShares iBonds Dec 2027 Term $ Corp UCITS ETF',
    'ID29': 'Ishares Ibonds Dec 2029 Term $ Corp Ucits Etf Acc',
    'ID30': 'Ishares Ibonds Dec 2030 Term $ Corp Ucits Etf Acc',
    'ID31US': 'ISHARES IBONDS DEC 2031 TERM $ CORP UCITS ETF USD (Acc)',
    'ID32': 'iShares iBonds Dec 2032 Term $ Corp UCITS ETF Acc.',
    'ID34': 'iShares iBonds Dec 2034 Term $ Corp UCITS ETF Acc',
    'IDTM': 'Ishares $ Treasury Bond 7-10Yr Etf Usd (Dist)',
    'IDTP': 'Ishares $ Tips Ucits Etf',
    'IEF': 'Ishares 7-10 Year Treasury Bond Etf',
    'IEFA': 'Ishares Core Msci Eafe Etf',
    'IEMB': 'iShares J.P. Morgan $ EM Bond UCITS ETF USD (DIST)',
    'IEMG': 'iShares Core MSCI Emerging Markets ETF',
    'IEUS': 'Ishares Msci Europe Small-Cap Etf',
    'IGLA': 'Ishares Global Govt Bond Ucits Etf Usd Acc',
    'IGM': 'iShares Expanded Tech Sector ETF',
    'IGSB': 'Ishares 1-5 Year Investment Grade Corporate Bond Etf',
    'IGV': 'Ishares Expanded Tech-Software Sector Etf',
    'IHI': 'Ishares U.S. Medical Devices Etf',
    'IHYA': 'Ishares Ii Plc Is $ Hy Corporate Bnd Ucits Etf Usd Acc',
    'IHYU': 'iShares $ High Yield Corp Bond UCITS ETF USD (DIST)',
    'IJPD': 'iShares MSCI Japan USD Hedged UCITS ETF USD (ACC)',
    'IJR': 'Ishares Core S&P Small-Cap Etf',
    'ILCUS': 'Inversiones La Construcción S.A.',
    'ILF': 'Ishares Latin America 40 Etf',
    'IMBA': 'iShares US Mortgage Backed Securities UCITS ETF U.S. Dollar (Accumulating)',
    'INCM': 'Franklin Income Focus ETF',
    'INDA': 'Ishares Msci India Etf',
    'INTC': 'Intel Corporation',
    'IOO': 'Ishares Global 100 Etf',
    'IQLT': 'Ishares Edge Msci Intl Quality Factor Etf',
    'ISAC': 'iSh MSCI All Country World UCITS ETF',
    'ISAUS': 'Interconexion Electrica S.A. E.S.P.',
    'ISEU': 'iShares Core MSCI Europe UCITS ETF EUR (DIST)',
    'ITAUCLUS': 'Banco Itaú Chile',
    'ITAUS': 'Ishares U.S. Aerospace & Defense Etf',
    'IU28': 'iShares iBonds Dec 2028 Term $ High Yield Corp UCITS ETF (ACC)',
    'IU29US': 'Ishares Ibonds Dec 2029 Term $ Hy Corp Ucits Etf',
    'IUAA': 'Ishares Us Aggregate Bond Ucits Etf Usd (Acc)',
    'IUAG': 'Ishares Us Aggregate Bond Ucits Etf Usd (Dist)',
    'IUFS': 'Ishares S&P 500 Financials Sector Ucits Etf Usd Acc',
    'IUIT': 'Ishares S&P 500 Information Technology Sector Ucits Etf Usd (Acc)',
    'IUQA': 'Ishares Edge Msci Usa Quality Factor Ucits Etf Usd (Acc)',
    'IUQD': 'iShares Edge MSCI USA Quality Factor UCITS ETF USD (DIST)',
    'IUSG': 'Ishares Core S&P U.S. Growth Etf',
    'IUVD': 'iShares Edge MSCI USA Value Factor UCITS ETF USD (DIST)',
    'IUVL': 'Ishares Edge Msci Usa Value Factor Ucits Etf',
    'IVE': 'Ishares S&P 500 Value Etf',
    'IVV': 'Ishares Core S&P 500 Etf',
    'IVVM': 'Ishares Large Cap Moderate Quarterly Ladder Etf',
    'IWF': 'Ishares Russell 1000 Growth Etf',
    'IWM': 'Ishares Russell 2000 Etf',
    'IWO': 'Ishares Russell 2000 Growth Etf',
    'IWQU': 'Ishares Edge Msci World Quality Factor Ucits Etf',
    'IYR': 'Ishares U.S. Real Estate Etf',
    'IYW': 'iShares U.S. Technology ETF',
    'JAAA': 'Janus Henderson USD AAA CLO Active Core UCITS ETF USD (ACC)',
    'JAAA1': 'Janus Henderson Aaa Clo Etf',
    'JEIA': 'JPM US Equity Premium Income Active UCITS ETF - USD (Acc)',
    'JEPG': 'Jpm Global Equity Premium Income Active Ucits Etf - Usd (Dist)',
    'JEPI': 'JPMorgan Equity Premium Income ETF',
    'JEPQ': 'JPMorgan Nasdaq Equity Premium Income ETF',
    'JETS': 'U.S. Global Jets Etf',
    'JNJ': 'Johnson & Johnson',
    'JNUG': 'Direxion Daily Junior Gold Miners Index Bull 2X Shares',
    'JPEA': 'Ishares J.P. Morgan $ Em Bond Ucits Etf',
    'JPM': 'Jpmorgan Chase & Co',
    'JREG': 'JPMORGAN ETFs (IRELAND) ICAV - GLOBAL RESEARCH ENHANCED INDEX EQUITY ACTIVE UCITS ETF - USD (ACC)',
    'JREU': 'JPMORGAN ETFs (IRELAND) ICAV - US RESEARCH ENHANCED INDEX EQUITY ACTIVE UCITS ETF - USD (ACC)',
    'K': 'Kinross Gold Corporation',
    'KHC': 'The Kraft Heinz Company',
    'KO': 'The Coca Cola Company',
    'KOLD': 'Proshares Ultra Short Bloomberg Natural Gas',
    'KRE': 'State Street SPDR S&P Regional Banking ETF',
    'KWEB': 'Kraneshares Csi China Internet Etf',
    'LABU': 'Direxion Daily S&P Biotech Bull 3X Shares',
    'LIT': 'Global X Lithium & Battery Tech Etf',
    'LLY': 'Eli Lilly And Company',
    'LMT': 'Lockheed Martin Corporation',
    'LQD': 'Ishares Iboxx $ Investment Grade Corporate Bond Etf',
    'LQDA': 'Ishares Plc Ishares $ Corp Bond Ucits Etf Usd (Acc)',
    'LQDE': 'iShares $ Corp Bond UCITS ETF USD (DIST)',
    'LTMUS': 'Latam Airlines Group S.A.',
    'MA': 'Mastercard Inc.',
    'MAGS': 'Roundhill Magnificent Seven ETF',
    'MALLPLUS': 'Plaza S.A.',
    'MCD': "Mcdonald'S Corporation",
    'MCHI': 'Ishares Msci China Etf',
    'MELI': 'Mercadolibre, Inc.',
    'META': 'Meta Platforms, Inc.',
    'METU': 'Direxion Daily Meta Bull 2X Shares',
    'MGK': 'Vanguard Morningstar Mega Cap Growth Etf',
    'MINEROUS': 'Mineros S.A.',
    'MMM': '3M Company',
    'MOAT': 'Vaneck Morningstar Wide Moat Etf',
    'MRK': 'Merck & Co., Inc',
    'MRNA': 'Moderna, Inc.',
    'MS': 'Morgan Stanley',
    'MSFT': 'Microsoft Corporation',
    'MSFU': 'Direxion Daily Msft Bull 2X Shares',
    'MSTR': 'Microstrategy Incorporated',
    'MU': 'Micron Technology, Inc.',
    'MUU': 'Direxion Daily Mu Bull 2X Shares',
    'N100': 'iShares NASDAQ 100 Swap UCITS ETF USD ACC',
    'NDIA': 'Ishares Msci India Ucits Etf Acc',
    'NEE': 'Nextera Energy Inc',
    'NEM': 'Newmont Corporation',
    'NFLX': 'Netflix, Inc.',
    'NFXL': 'Direxion Daily Nflx Bull 2X Shares',
    'NKE': 'Nike, Inc.',
    'NLR': 'VanEck Uranium and Nuclear ETF',
    'NOBL': 'Proshares S&P 500 Dividend Aristocrats Etf',
    'NOWUS': 'Servicenow, Inc.',
    'NUGT': 'Direxion Daily Gold Miners Index Bull 2X Shares',
    'NVDA': 'Nvidia Corporation',
    'NVDL': 'Graniteshares 2X Long Nvda Daily Etf',
    'ON': 'On Semiconductor Corporation',
    'ORCL': 'Oracle Corporation',
    'ORCX': 'Defiance Daily Target 2X Long ORCL ETF',
    'OXY': 'Occidental Petroleum Corporation',
    'PANW': 'Palo Alto Networks, Inc.',
    'PARAUCUS': 'Parque Arauco S.A.',
    'PAVE': 'Global X U.S. Infrastructure Development Etf',
    'PAVE1US': 'Global X U.S. Infrastructure Development Ucits Etf Acc',
    'PDD': 'Pdd Holdings Inc.',
    'PEIUS': 'Patrimonio Autonomo Estrategias Inmobiliarias',
    'PEP': 'Pepsico, Inc.',
    'PFAVALUS': 'Grupo Aval Acciones Y Valores S.A.',
    'PFCIBEUS': 'Grupo Cibest S.A.',
    'PFCORFUS': 'Corporación Financiera Colombiana S.A.',
    'PFDAVIUS': 'Banco Davivienda S.A.',
    'PFE': 'Pfizer Inc',
    'PFGARGUS': 'Grupo Argos S.A.',
    'PFSURAUS': 'Grupo De Inversiones Suramericana S.A.',
    'PG': 'The Procter & Gamble Company',
    'PGHYUS': 'Invesco Global ex-US High Yield Corporate Bond ETF',
    'PLTR': 'Palantir Technologies',
    'PLTU': 'Direxion Daily Pltr Bull 2X Shares',
    'PROMIGUS': 'Promigas S.A. E.S.P.',
    'PSIUS': 'Invesco Semiconductors Etf',
    'PSKY': 'Paramount Skydance Corporation',
    'PYPL': 'Paypal Holdings, Inc.',
    'QCOM': 'Qualcomm Incorporated',
    'QGRW': 'WisdomTree U.S. Quality Growth Fund',
    'QGRW1': 'Wisdomtree Us Quality Growth Ucits Etf Usd Acc',
    'QQQ': 'Invesco Qqq Trust, Series 1',
    'QQQM': 'Invesco Nasdaq 100 Etf',
    'QTUM': 'Defiance Quantum ETF',
    'QUAL': 'Ishares Edge Msci Usa Quality Factor Etf',
    'QUINENUS': 'Quiñenco S.A.',
    'QYLD': 'Global X Nasdaq 100 Covered Call Etf',
    'R1GR': 'Ishares Russell 1000 Growth Ucits Etf',
    'R2US': 'Spdr Russell 2000 U.S. Small Cap Ucits Etf (Acc)',
    'REGN': 'Regeneron Pharmaceuticals, Inc.',
    'REMX': 'Vaneck Rare Earth And Strategic Metals Etf',
    'RIPLEYUS': 'Ripley Corp S.A.',
    'RSP': 'Invesco S&P 500 Equal Weight Etf',
    'RYLD': 'Russell 2000 Covered Call ETF',
    'SALFACUS': 'Salfacorp S.A.',
    'SBUX': 'Starbucks Corporation',
    'SCHD': 'Schwab Us Dividend Equity Etf',
    'SDHA': 'ISHARES $ SHORT DURATION HIGH YIELD CORP BOND  UCITS ETF USD (Acc)',
    'SDIA': 'Ishares $ Short Duration Corp Bond Ucits Etf',
    'SDIG': 'iShares $ Short Duration Corp Bond UCITS ETF USD (DIST)',
    'SDVY': 'First Trust Smid Cap Rising Dividend Achievers Etf',
    'SEA': 'U.S. Global Sea to Sky Cargo ETF',
    'SGDJ': 'Sprott Junior Gold Miners ETF',
    'SHLD': 'Global X Defense Tech Etf',
    'SHOP': 'Shopify Inc.',
    'SHY': 'Ishares 1-3 Year Treasury Bond Etf',
    'SIL': 'Global X Silver Miners Etf',
    'SILJ': 'Amplify Junior Silver Miners ETF',
    'SLB': 'SLB N.V. (SLB Limited)',
    'SLON': 'ProShares Ultra Solana ETF',
    'SLV': 'Ishares Silver Trust',
    'SLVR': 'Sprott Silver Miners & Physical Silver ETF',
    'SMCI': 'Super Micro Computer, Inc.',
    'SMH': 'Vaneck Semiconductor Etf',
    'SMIN': 'Ishares Msci India Small-Cap Etf',
    'SMT/UK': 'Scottish Mortgage Investment Trust Plc',
    'SMUUS': 'Smu S.A.',
    'SNDKUS': 'Sandisk Corporation',
    'SOXL': 'Direxion Daily Semiconductor Bull 3X Shares',
    'SOXX': 'Ishares Semiconductor Etf',
    'SPCXUS': 'Space Exploration Technologies Corp.',
    'SPEQ': 'Invesco S&P 500 Equal Weight Ucits Etf Acc',
    'SPGIUS': 'S&P Global Inc.',
    'SPGP': 'Invesco S&P 500 Garp Etf',
    'SPHQ': 'Invesco S&P 500 Quality Etf',
    'SPMOUS': 'Invesco S&P 500 Momentum Etf',
    'SPSM': 'State Street SPDR Portfolio S&P 600 Small Cap ETF',
    'SPXL': 'Direxion Daily S&P 500 Bull 3X Shares',
    'SPY': 'Standard & Dr Trust Series I',
    'SPYG': 'State Street SPDR Portfolio S&P 500 Growth ETF',
    'SPYI': 'NEOS S&P 500 High Income ETF',
    'SPYL': 'SPDR S&P 500 UCITS ETF (Acc)',
    'SPYM': 'State Street SPDR Portfolio S&P 500 ETF',
    'SQMBUS': 'Sociedad Quimica Y Minera De Chile S.A.',
    'SQQQ': 'Proshares Ultrapro Short Qqq',
    'SRET': 'Global X Superdividend Reit Etf',
    'SRLN': 'State Street Blackstone Senior Loan ETF',
    'SSO': 'Proshares Ultra S&P500®',
    'STXUS': 'Seagate Technology Holdings Plc',
    'STYC': 'Pimco Us Short-Term High Yield Corporate Bond Ucits Etf (Acc)',
    'STZ': 'Constellation Brands Inc',
    'T': 'At&T Inc.',
    'TECL': 'Direxion Daily Technology Bull 3X Shares',
    'TERPELUS': 'Organizacion Terpel S.A.',
    'TFLOUS': 'iShares Treasury Floating Rate Bond ETF',
    'TGT': 'Target Corporation',
    'TI5A': 'Ishares $ Tips 0-5 Ucits Etf Usd Acc',
    'TIP': 'Ishares Tips Bond Etf',
    'TLH': 'Ishares 10-20 Year Treasury Bond Etf',
    'TLT': 'Ishares 20+ Year Treasury Bond Etf',
    'TLTW': 'iShares 20+ Year Treasury Bond BuyWrite Strategy ETF',
    'TMF': 'Direxion Daily 20+ Year Treasury Bull 3X Shares',
    'TMO': 'Thermo Fisher Scientific Inc.',
    'TMUS': 'T-Mobile Us Inc.',
    'TQQQ': 'Proshares Ultrapro Qqq®',
    'TSLA': 'Tesla, Inc.',
    'TSLL': 'Direxion Daily TSLA Bull 2X Shares',
    'TSMUS': 'Taiwan Semiconductor Manufacturing Company Limited',
    'TTD': 'The Trade Desk, Inc.',
    'UAE': 'iShares MSCI UAE ETF',
    'UAL': 'United Airlines Holdings, Inc.',
    'UBER': 'Uber Technologies, Inc.',
    'UCO': 'Proshares Ultra Bloomberg Crude Oil',
    'UDVD': 'Spdr S&P U.S. Dividend Aristocrats Ucits Etf',
    'UNH': 'Unitedhealth Group Inc',
    'UPRO': 'Proshares Ultrapro S&P500',
    'UPS': 'United Parcel Service, Inc.',
    'URA': 'Global X Uranium ETF',
    'USC5US': 'STATE STREET SPDR BLOOMBERG 1-5 YEAR U.S. CORPORATE BOND UCITS ETF (Acc)',
    'USD1': 'Proshares Ultra Semiconductors (Usd)',
    'USMV': 'Ishares Msci Usa Min Vol Factor Etf',
    'USO': 'United States Oil Fund, Lp',
    'UUP': 'Invesco Db Us Dollar Index Bullish Fund',
    'V': 'Visa Inc',
    'VAPOREUS': 'Compañía Sud Americana De Vapores S.A.',
    'VB': 'Vanguard Morningstar Small-Cap Etf',
    'VBRUS': 'Vanguard Morningstar Small-Cap Value Etf',
    'VCIT': 'Vanguard Intermediate-Term Corporate Bond Etf',
    'VDPA': 'Vanguard USD Corporate Bond UCITS ETF (USD) Accumulating',
    'VDSTUS': 'Vanguard U.S. Treasury 0-1 Year Bond Ucits Etf - (Usd) Accumulating',
    'VDTA': 'Vanguard USD Treasury Bond UCITS ETF Acc',
    'VEA': 'Vanguard Ftse Developed Markets Etf',
    'VFEAUS': 'Vanguard Ftse Emerging Markets Ucits Etf - (Usd) Accumulating',
    'VGK': 'Vanguard Ftse Europe Etf',
    'VGT': 'Vanguard Information Technology Etf',
    'VHYA': 'Vanguard FTSE All-World High Dividend Yield UCITS ETF - (USD) Accumulating',
    'VJPU': 'Vanguard FTSE Japan UCITS ETF - USD Hedged Accumulating',
    'VNLA': 'Janus Henderson Short Duration Income Etf',
    'VOO': 'Vanguard S&P 500 Etf',
    'VT': 'Vanguard Total World Stock Etf',
    'VTI': 'Vanguard Morningstar Total Stock Market Etf',
    'VTV': 'Vanguard Morningstar Value Etf',
    'VUAA': 'Vanguard S&P 500 UCITS ETF (USD) Accumulating',
    'VUGUS': 'Vanguard Morningstar Growth Etf',
    'VWO': 'Vanguard Ftse Emerging Markets Etf',
    'VWRA': 'Vanguard Ftse All-World Ucits Etf Usd Acc',
    'VXUS': 'Vanguard Total International Stock Etf',
    'VZ': 'Verizon Communications Inc',
    'WDEFUS': 'WisdomTree Europe Defense Fund',
    'WFC': 'Wells Fargo & Company',
    'WIAU': 'ISHARES FALLEN ANGELS HIGH YIELD CORP BOND UCITS ETF USD (Acc)',
    'WMT': 'Walmart Inc.',
    'WPM': 'Wheaton Precious Metals Corp.',
    'XAR': 'State Street Spdr S&P Aerospace & Defense Etf',
    'XBI': 'State Street SPDR S&P Biotech ETF',
    'XEOU': 'Xtrackers MSCI Europe UCITS ETF 2C USD Hedged',
    'XLC': 'State Street Communication Services Select Sector Spdr Etf',
    'XLE': 'State Street Energy Select Sector SPDR ETF',
    'XLF': 'State Street Financial Select Sector Spdr Etf',
    'XLI': 'Industrial Select Sector Spdr Fund',
    'XLK': 'State Street Technology Select Sector Spdr Etf',
    'XLP': 'State Street Consumer Staples Select Sector Spdr Etf',
    'XLRE': 'State Street Real Estate Select Sector Spdr Etf',
    'XLU': 'State Street Utilities Select Sector Spdr Etf',
    'XLV': 'State Street Health Care Select Sector SPDR ETF',
    'XLY': 'State Street Consumer Discretionary Select Sector SPDR ETF',
    'XMED': 'Xtrackers Msci Europe UCITS ETF 1C',
    'XNTK': 'State Street SPDR NYSE Technology ETF',
    'XOM': 'Exxonmobil Holdings Corporation',
    'XYLD': 'Global X S&P 500 Covered Call Etf',
    'XYZ': 'Block, Inc.',
    'YINN': 'Direxion Daily FTSE China Bull 3X Shares',
    'ZAP': 'Global X U.S. Electrification ETF',
    'ZM': 'Zoom Video Communications, Inc',
    'ZTS': 'Zoetis Inc.',
}

BVL_TICKERS = sorted(BVL_SECTORS.keys())
